// Code generated by Kitex v0.16.1. DO NOT EDIT.

package chathistoryservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	chathistory "yikou-ai-go-microservice/services/app/kitex_gen/chathistory"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"LoadChatHistoryToMemory": kitex.NewMethodInfo(
		loadChatHistoryToMemoryHandler,
		newLoadChatHistoryToMemoryArgs,
		newLoadChatHistoryToMemoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	chatHistoryServiceServiceInfo                = NewServiceInfo()
	chatHistoryServiceServiceInfoForClient       = NewServiceInfoForClient()
	chatHistoryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chatHistoryServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chatHistoryServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chatHistoryServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ChatHistoryService"
	handlerType := (*chathistory.ChatHistoryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "yikou.chathistory",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func loadChatHistoryToMemoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(chathistory.LoadChatHistoryToMemoryRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(chathistory.ChatHistoryService).LoadChatHistoryToMemory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LoadChatHistoryToMemoryArgs:
		success, err := handler.(chathistory.ChatHistoryService).LoadChatHistoryToMemory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoadChatHistoryToMemoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLoadChatHistoryToMemoryArgs() interface{} {
	return &LoadChatHistoryToMemoryArgs{}
}

func newLoadChatHistoryToMemoryResult() interface{} {
	return &LoadChatHistoryToMemoryResult{}
}

type LoadChatHistoryToMemoryArgs struct {
	Req *chathistory.LoadChatHistoryToMemoryRequest
}

func (p *LoadChatHistoryToMemoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoadChatHistoryToMemoryArgs) Unmarshal(in []byte) error {
	msg := new(chathistory.LoadChatHistoryToMemoryRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoadChatHistoryToMemoryArgs_Req_DEFAULT *chathistory.LoadChatHistoryToMemoryRequest

func (p *LoadChatHistoryToMemoryArgs) GetReq() *chathistory.LoadChatHistoryToMemoryRequest {
	if !p.IsSetReq() {
		return LoadChatHistoryToMemoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoadChatHistoryToMemoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoadChatHistoryToMemoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoadChatHistoryToMemoryResult struct {
	Success *chathistory.LoadChatHistoryToMemoryResponse
}

var LoadChatHistoryToMemoryResult_Success_DEFAULT *chathistory.LoadChatHistoryToMemoryResponse

func (p *LoadChatHistoryToMemoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoadChatHistoryToMemoryResult) Unmarshal(in []byte) error {
	msg := new(chathistory.LoadChatHistoryToMemoryResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoadChatHistoryToMemoryResult) GetSuccess() *chathistory.LoadChatHistoryToMemoryResponse {
	if !p.IsSetSuccess() {
		return LoadChatHistoryToMemoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoadChatHistoryToMemoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*chathistory.LoadChatHistoryToMemoryResponse)
}

func (p *LoadChatHistoryToMemoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoadChatHistoryToMemoryResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) LoadChatHistoryToMemory(ctx context.Context, Req *chathistory.LoadChatHistoryToMemoryRequest) (r *chathistory.LoadChatHistoryToMemoryResponse, err error) {
	var _args LoadChatHistoryToMemoryArgs
	_args.Req = Req
	var _result LoadChatHistoryToMemoryResult
	if err = p.c.Call(ctx, "LoadChatHistoryToMemory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
