// Code generated by Kitex v0.16.1. DO NOT EDIT.
package chathistoryservice

import (
	server "github.com/cloudwego/kitex/server"
	chathistory "yikou-ai-go-microservice/services/app/kitex_gen/chathistory"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler chathistory.ChatHistoryService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler chathistory.ChatHistoryService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
