server:
  port: 8124
  context-path: /api
  config-active: local
  enable-metric: true
  metric-port: 9091
  metric-path: /prometheus

database:
  host: 192.168.10.101
  port: 3306
  username: root
  password: 815256031Hc!
  dbname: yikou_ai

ai:
  chat-model:
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api-key: <你的api-key>
    model-name: deepseek-v3.2
    memory-store: redis
    memory-ttl: 3600
  reasoning-chat-model:
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api-key: <你的api-key>
    model-name: deepseek-v3.2
    memory-store: redis
    memory-ttl: 3600

redis:
  host: 192.168.10.101
  port: 6379
  password: ""
  db: 0

# 腾讯云COS对象存储配置
cos:
  # 自定义域名（可选）
  host: ""
  # 腾讯云SecretId
  secret-id: ""
  # 腾讯云SecretKey
  secret-key: ""
  # 地域简称
  region: ""
  # 存储桶名称
  bucket: ""

# Pexels 图片搜索配置
pexels:
  api-key: <Your API Key>

# 阿里云 DashScope 配置
dashscope:
  api-key: <Your API Key>
  image-model: wan2.2-t2i-flash

# Nacos 服务注册配置
nacos:
  host: localhost
  port: 8848
  namespace-id: public
  username: nacos
  password: nacos
  log-dir: /tmp/nacos/log
  cache-dir: /tmp/nacos/cache
  log-level: info


