// Code generated by hertz generator.

package main

import (
	"context"
	"fmt"
	"github.com/bytedance/gopkg/util/logger"
	"github.com/cloudwego/eino-ext/devops"
	"os"
	"os/signal"
	"syscall"
	_ "workspace-yikou-ai-go/biz/dal"
	"workspace-yikou-ai-go/pkg/myutils"
	"workspace-yikou-ai-go/wire"
)

func main() {
	h, err := wire.InitializeApp()
	if err != nil {
		panic(fmt.Errorf("注入失败: %w", err))
	}

	ctx := context.Background()
	err = devops.Init(ctx)
	if err != nil {
		logger.Errorf("[eino dev] init failed, err=%v", err)
	}

	go func() {
		quit := make(chan os.Signal, 1)
		signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
		<-quit
		myutils.CloseBrowser()
	}()

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sigs
		logger.Infof("[eino dev] shutting down\n")
		h.Close()
	}()

	h.Spin()
}
