// Code generated by hertz generator.

package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	_ "workspace-yikou-ai-go/biz/dal"
	"workspace-yikou-ai-go/pkg/myutils"
	"workspace-yikou-ai-go/wire"
)

func main() {
	h, err := wire.InitializeApp()
	if err != nil {
		panic(fmt.Errorf("注入失败: %w", err))
	}

	go func() {
		quit := make(chan os.Signal, 1)
		signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
		<-quit
		myutils.CloseBrowser()
	}()

	h.Spin()
}
