// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
	"workspace-yikou-ai-go/biz/handler"
	app "workspace-yikou-ai-go/biz/handler/app"
	user "workspace-yikou-ai-go/biz/handler/user"
	middleware "workspace-yikou-ai-go/biz/middleware"
	"workspace-yikou-ai-go/biz/model/enum"
	_ "workspace-yikou-ai-go/docs"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz, url func(config *swagger.Config)) {
	r.GET("/ping", handler.Ping)
	r.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler, url))

	userRoute := r.Group("/user")
	{
		userHandler := user.NewUserHandler()
		userRoute.POST("/register", userHandler.UserRegister)
		userRoute.POST("/login", userHandler.UserLogin)
		userRoute.GET("/get/vo", userHandler.GetUserVo)

		// 需要登录的接口
		userRoute.GET("/get/login", middleware.AuthMiddleware(enum.UserRole), userHandler.GetLoginUser)
		userRoute.POST("/logout", middleware.AuthMiddleware(enum.UserRole), userHandler.Logout)

		// 需要管理员权限的接口
		userRoute.POST("/add", middleware.AuthMiddleware(enum.AdminRole), userHandler.AddUser)
		userRoute.GET("/get", middleware.AuthMiddleware(enum.AdminRole), userHandler.GetUser)
		userRoute.POST("/delete", middleware.AuthMiddleware(enum.AdminRole), userHandler.DeleteUser)
		userRoute.POST("/update", middleware.AuthMiddleware(enum.AdminRole), userHandler.UpdateUser)
		userRoute.POST("/list/page/vo", middleware.AuthMiddleware(enum.AdminRole), userHandler.ListUserVoByPage)
	}

	appRoute := r.Group("/app")
	{
		appHandler := app.NewAppHandler()
		appRoute.POST("/good/list/page/vo", appHandler.ListGoodApp)
		appRoute.GET("/get/vo", middleware.AuthMiddleware(enum.UserRole), appHandler.GetAppVo)

		// 需要登录的接口
		appRoute.POST("/my/list/page/vo", middleware.AuthMiddleware(enum.UserRole), appHandler.ListMyApp)
		appRoute.POST("/add", middleware.AuthMiddleware(enum.UserRole), appHandler.AddApp)
		appRoute.POST("/update", middleware.AuthMiddleware(enum.UserRole), appHandler.UpdateApp)
		appRoute.POST("/delete", middleware.AuthMiddleware(enum.UserRole), appHandler.DeleteApp)
		appRoute.POST("/chat/gen/code", middleware.AuthMiddleware(enum.UserRole), appHandler.ChatToGenCode)
		appRoute.POST("/deploy", middleware.AuthMiddleware(enum.UserRole), appHandler.DeployApp)

		// 需要管理员权限的接口
		appRoute.POST("/admin/update", middleware.AuthMiddleware(enum.AdminRole), appHandler.AdminUpdateApp)
		appRoute.POST("/admin/delete", middleware.AuthMiddleware(enum.AdminRole), appHandler.AdminDeleteApp)
		appRoute.GET("/admin/get/vo", middleware.AuthMiddleware(enum.AdminRole), appHandler.AdminGetAppVo)
		appRoute.POST("/admin/list/page/vo", middleware.AuthMiddleware(enum.AdminRole), appHandler.AdminListApp)
	}
}
