// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitex_gen

import (
	"context"

	"github.com/cloudwego/prutal"
)

type GenerateAndUploadScreenshotRequest struct {
	WebUrl string `protobuf:"bytes,1,opt,name=WebUrl" json:"WebUrl,omitempty"`
}

func (x *GenerateAndUploadScreenshotRequest) Reset() { *x = GenerateAndUploadScreenshotRequest{} }

func (x *GenerateAndUploadScreenshotRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateAndUploadScreenshotRequest) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *GenerateAndUploadScreenshotRequest) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

type GenerateAndUploadScreenshotResponse struct {
	SaveUrl string `protobuf:"bytes,1,opt,name=saveUrl" json:"saveUrl,omitempty"`
}

func (x *GenerateAndUploadScreenshotResponse) Reset() { *x = GenerateAndUploadScreenshotResponse{} }

func (x *GenerateAndUploadScreenshotResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateAndUploadScreenshotResponse) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *GenerateAndUploadScreenshotResponse) GetSaveUrl() string {
	if x != nil {
		return x.SaveUrl
	}
	return ""
}

type ScreenshotService interface {
	GenerateAndUploadScreenshot(ctx context.Context, req *GenerateAndUploadScreenshotRequest) (res *GenerateAndUploadScreenshotResponse, err error)
}
