// Code generated by Kitex v0.16.1. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	kitex_gen "yikou-ai-go-microservice/services/user/kitex_gen"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListByIds(ctx context.Context, Req *kitex_gen.ListByIdsRequest, callOptions ...callopt.Option) (r *kitex_gen.ListByIdsResponse, err error)
	GetById(ctx context.Context, Req *kitex_gen.GetByIdRequest, callOptions ...callopt.Option) (r *kitex_gen.GetByIdResponse, err error)
	GetUserVo(ctx context.Context, Req *kitex_gen.GetUserVORequest, callOptions ...callopt.Option) (r *kitex_gen.GetUserVOResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) ListByIds(ctx context.Context, Req *kitex_gen.ListByIdsRequest, callOptions ...callopt.Option) (r *kitex_gen.ListByIdsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListByIds(ctx, Req)
}

func (p *kUserServiceClient) GetById(ctx context.Context, Req *kitex_gen.GetByIdRequest, callOptions ...callopt.Option) (r *kitex_gen.GetByIdResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetById(ctx, Req)
}

func (p *kUserServiceClient) GetUserVo(ctx context.Context, Req *kitex_gen.GetUserVORequest, callOptions ...callopt.Option) (r *kitex_gen.GetUserVOResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserVo(ctx, Req)
}
