// Code generated by Kitex v0.16.1. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	kitex_gen "yikou-ai-go-microservice/services/user/kitex_gen"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListByIds": kitex.NewMethodInfo(
		listByIdsHandler,
		newListByIdsArgs,
		newListByIdsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetById": kitex.NewMethodInfo(
		getByIdHandler,
		newGetByIdArgs,
		newGetByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserVo": kitex.NewMethodInfo(
		getUserVoHandler,
		newGetUserVoArgs,
		newGetUserVoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetLoginUserBySessionId": kitex.NewMethodInfo(
		getLoginUserBySessionIdHandler,
		newGetLoginUserBySessionIdArgs,
		newGetLoginUserBySessionIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*kitex_gen.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "yikou.user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func listByIdsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.ListByIdsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.UserService).ListByIds(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListByIdsArgs:
		success, err := handler.(kitex_gen.UserService).ListByIds(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListByIdsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListByIdsArgs() interface{} {
	return &ListByIdsArgs{}
}

func newListByIdsResult() interface{} {
	return &ListByIdsResult{}
}

type ListByIdsArgs struct {
	Req *kitex_gen.ListByIdsRequest
}

func (p *ListByIdsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListByIdsArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.ListByIdsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListByIdsArgs_Req_DEFAULT *kitex_gen.ListByIdsRequest

func (p *ListByIdsArgs) GetReq() *kitex_gen.ListByIdsRequest {
	if !p.IsSetReq() {
		return ListByIdsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListByIdsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListByIdsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListByIdsResult struct {
	Success *kitex_gen.ListByIdsResponse
}

var ListByIdsResult_Success_DEFAULT *kitex_gen.ListByIdsResponse

func (p *ListByIdsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListByIdsResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.ListByIdsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListByIdsResult) GetSuccess() *kitex_gen.ListByIdsResponse {
	if !p.IsSetSuccess() {
		return ListByIdsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListByIdsResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.ListByIdsResponse)
}

func (p *ListByIdsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListByIdsResult) GetResult() interface{} {
	return p.Success
}

func getByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GetByIdRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.UserService).GetById(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetByIdArgs:
		success, err := handler.(kitex_gen.UserService).GetById(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetByIdResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetByIdArgs() interface{} {
	return &GetByIdArgs{}
}

func newGetByIdResult() interface{} {
	return &GetByIdResult{}
}

type GetByIdArgs struct {
	Req *kitex_gen.GetByIdRequest
}

func (p *GetByIdArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetByIdArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetByIdRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetByIdArgs_Req_DEFAULT *kitex_gen.GetByIdRequest

func (p *GetByIdArgs) GetReq() *kitex_gen.GetByIdRequest {
	if !p.IsSetReq() {
		return GetByIdArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetByIdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetByIdArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetByIdResult struct {
	Success *kitex_gen.GetByIdResponse
}

var GetByIdResult_Success_DEFAULT *kitex_gen.GetByIdResponse

func (p *GetByIdResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetByIdResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetByIdResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetByIdResult) GetSuccess() *kitex_gen.GetByIdResponse {
	if !p.IsSetSuccess() {
		return GetByIdResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetByIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GetByIdResponse)
}

func (p *GetByIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetByIdResult) GetResult() interface{} {
	return p.Success
}

func getUserVoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GetUserVORequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.UserService).GetUserVo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserVoArgs:
		success, err := handler.(kitex_gen.UserService).GetUserVo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserVoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserVoArgs() interface{} {
	return &GetUserVoArgs{}
}

func newGetUserVoResult() interface{} {
	return &GetUserVoResult{}
}

type GetUserVoArgs struct {
	Req *kitex_gen.GetUserVORequest
}

func (p *GetUserVoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserVoArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetUserVORequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserVoArgs_Req_DEFAULT *kitex_gen.GetUserVORequest

func (p *GetUserVoArgs) GetReq() *kitex_gen.GetUserVORequest {
	if !p.IsSetReq() {
		return GetUserVoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserVoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserVoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserVoResult struct {
	Success *kitex_gen.GetUserVOResponse
}

var GetUserVoResult_Success_DEFAULT *kitex_gen.GetUserVOResponse

func (p *GetUserVoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserVoResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetUserVOResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserVoResult) GetSuccess() *kitex_gen.GetUserVOResponse {
	if !p.IsSetSuccess() {
		return GetUserVoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserVoResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GetUserVOResponse)
}

func (p *GetUserVoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserVoResult) GetResult() interface{} {
	return p.Success
}

func getLoginUserBySessionIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GetLoginUserBySessionIdRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.UserService).GetLoginUserBySessionId(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetLoginUserBySessionIdArgs:
		success, err := handler.(kitex_gen.UserService).GetLoginUserBySessionId(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetLoginUserBySessionIdResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}

func newGetLoginUserBySessionIdArgs() interface{} {
	return &GetLoginUserBySessionIdArgs{}
}

func newGetLoginUserBySessionIdResult() interface{} {
	return &GetLoginUserBySessionIdResult{}
}

type GetLoginUserBySessionIdArgs struct {
	Req *kitex_gen.GetLoginUserBySessionIdRequest
}

func (p *GetLoginUserBySessionIdArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetLoginUserBySessionIdArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetLoginUserBySessionIdRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetLoginUserBySessionIdArgs_Req_DEFAULT *kitex_gen.GetLoginUserBySessionIdRequest

func (p *GetLoginUserBySessionIdArgs) GetReq() *kitex_gen.GetLoginUserBySessionIdRequest {
	if !p.IsSetReq() {
		return GetLoginUserBySessionIdArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetLoginUserBySessionIdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetLoginUserBySessionIdArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetLoginUserBySessionIdResult struct {
	Success *kitex_gen.GetLoginUserBySessionIdResponse
}

var GetLoginUserBySessionIdResult_Success_DEFAULT *kitex_gen.GetLoginUserBySessionIdResponse

func (p *GetLoginUserBySessionIdResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetLoginUserBySessionIdResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetLoginUserBySessionIdResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetLoginUserBySessionIdResult) GetSuccess() *kitex_gen.GetLoginUserBySessionIdResponse {
	if !p.IsSetSuccess() {
		return GetLoginUserBySessionIdResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetLoginUserBySessionIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GetLoginUserBySessionIdResponse)
}

func (p *GetLoginUserBySessionIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetLoginUserBySessionIdResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListByIds(ctx context.Context, Req *kitex_gen.ListByIdsRequest) (r *kitex_gen.ListByIdsResponse, err error) {
	var _args ListByIdsArgs
	_args.Req = Req
	var _result ListByIdsResult
	if err = p.c.Call(ctx, "ListByIds", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetById(ctx context.Context, Req *kitex_gen.GetByIdRequest) (r *kitex_gen.GetByIdResponse, err error) {
	var _args GetByIdArgs
	_args.Req = Req
	var _result GetByIdResult
	if err = p.c.Call(ctx, "GetById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserVo(ctx context.Context, Req *kitex_gen.GetUserVORequest) (r *kitex_gen.GetUserVOResponse, err error) {
	var _args GetUserVoArgs
	_args.Req = Req
	var _result GetUserVoResult
	if err = p.c.Call(ctx, "GetUserVo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLoginUserBySessionId(ctx context.Context, Req *kitex_gen.GetLoginUserBySessionIdRequest) (r *kitex_gen.GetLoginUserBySessionIdResponse, err error) {
	var _args GetLoginUserBySessionIdArgs
	_args.Req = Req
	var _result GetLoginUserBySessionIdResult
	if err = p.c.Call(ctx, "GetLoginUserBySessionId", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
