// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitex_gen

import (
	"context"

	"github.com/cloudwego/prutal"
)

// 用户信息（对应 GORM Model）
type User struct {
	Id           int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`                      // id
	UserAccount  string `protobuf:"bytes,2,opt,name=user_account" json:"user_account,omitempty"`   // 账号
	UserPassword string `protobuf:"bytes,3,opt,name=user_password" json:"user_password,omitempty"` // 密码
	UserName     string `protobuf:"bytes,4,opt,name=user_name" json:"user_name,omitempty"`         // 用户昵称
	UserAvatar   string `protobuf:"bytes,5,opt,name=user_avatar" json:"user_avatar,omitempty"`     // 用户头像
	UserProfile  string `protobuf:"bytes,6,opt,name=user_profile" json:"user_profile,omitempty"`   // 用户简介
	UserRole     string `protobuf:"bytes,7,opt,name=user_role" json:"user_role,omitempty"`         // 用户角色：user/admin
	EditTime     int64  `protobuf:"varint,8,opt,name=edit_time" json:"edit_time,omitempty"`        // 编辑时间（时间戳）
	CreateTime   int64  `protobuf:"varint,9,opt,name=create_time" json:"create_time,omitempty"`    // 创建时间（时间戳）
	UpdateTime   int64  `protobuf:"varint,10,opt,name=update_time" json:"update_time,omitempty"`   // 更新时间（时间戳）
	IsDelete     int32  `protobuf:"varint,11,opt,name=is_delete" json:"is_delete,omitempty"`       // 是否删除
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUserAccount() string {
	if x != nil {
		return x.UserAccount
	}
	return ""
}

func (x *User) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *User) GetUserProfile() string {
	if x != nil {
		return x.UserProfile
	}
	return ""
}

func (x *User) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *User) GetEditTime() int64 {
	if x != nil {
		return x.EditTime
	}
	return 0
}

func (x *User) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *User) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *User) GetIsDelete() int32 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

// 用户视图对象（对应 UserVO）
type UserVO struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`                    // id
	UserAccount string `protobuf:"bytes,2,opt,name=user_account" json:"user_account,omitempty"` // 账号
	UserName    string `protobuf:"bytes,3,opt,name=user_name" json:"user_name,omitempty"`       // 用户昵称
	UserAvatar  string `protobuf:"bytes,4,opt,name=user_avatar" json:"user_avatar,omitempty"`   // 用户头像
	UserProfile string `protobuf:"bytes,5,opt,name=user_profile" json:"user_profile,omitempty"` // 用户简介
	UserRole    string `protobuf:"bytes,6,opt,name=user_role" json:"user_role,omitempty"`       // 用户角色
	CreateTime  int64  `protobuf:"varint,7,opt,name=create_time" json:"create_time,omitempty"`  // 创建时间（时间戳）
	UpdateTime  int64  `protobuf:"varint,8,opt,name=update_time" json:"update_time,omitempty"`  // 更新时间（时间戳）
}

func (x *UserVO) Reset() { *x = UserVO{} }

func (x *UserVO) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserVO) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserVO) GetUserAccount() string {
	if x != nil {
		return x.UserAccount
	}
	return ""
}

func (x *UserVO) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserVO) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *UserVO) GetUserProfile() string {
	if x != nil {
		return x.UserProfile
	}
	return ""
}

func (x *UserVO) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *UserVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 根据ID列表查询用户请求
type ListByIdsRequest struct {
	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
}

func (x *ListByIdsRequest) Reset() { *x = ListByIdsRequest{} }

func (x *ListByIdsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListByIdsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListByIdsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 根据ID列表查询用户响应
type ListByIdsResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (x *ListByIdsResponse) Reset() { *x = ListByIdsResponse{} }

func (x *ListByIdsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListByIdsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListByIdsResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// 根据ID查询用户请求
type GetByIdRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *GetByIdRequest) Reset() { *x = GetByIdRequest{} }

func (x *GetByIdRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetByIdRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 根据ID查询用户响应
type GetByIdResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *GetByIdResponse) Reset() { *x = GetByIdResponse{} }

func (x *GetByIdResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetByIdResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 获取用户视图对象请求
type GetUserVORequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *GetUserVORequest) Reset() { *x = GetUserVORequest{} }

func (x *GetUserVORequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserVORequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserVORequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 获取用户视图对象响应
type GetUserVOResponse struct {
	UserVo *UserVO `protobuf:"bytes,1,opt,name=user_vo" json:"user_vo,omitempty"`
}

func (x *GetUserVOResponse) Reset() { *x = GetUserVOResponse{} }

func (x *GetUserVOResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserVOResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserVOResponse) GetUserVo() *UserVO {
	if x != nil {
		return x.UserVo
	}
	return nil
}

type UserService interface {
	ListByIds(ctx context.Context, req *ListByIdsRequest) (res *ListByIdsResponse, err error)
	GetById(ctx context.Context, req *GetByIdRequest) (res *GetByIdResponse, err error)
	GetUserVo(ctx context.Context, req *GetUserVORequest) (res *GetUserVOResponse, err error)
}
