// Code generated by Kitex v0.16.1. DO NOT EDIT.

package kitex_gen

import (
	"context"
	"strconv"

	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/prutal"
)

// 代码生成类型枚举
type CodeGenType int32

const (
	CodeGenType_HTML        CodeGenType = 0
	CodeGenType_MULTI_FILE  CodeGenType = 1
	CodeGenType_VUE_PROJECT CodeGenType = 2
)

// Enum value maps for CodeGenType.
var CodeGenType_name = map[int32]string{
	0: "HTML",
	1: "MULTI_FILE",
	2: "VUE_PROJECT",
}

var CodeGenType_value = map[string]int32{
	"HTML":        0,
	"MULTI_FILE":  1,
	"VUE_PROJECT": 2,
}

func (x CodeGenType) String() string {
	s, ok := CodeGenType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 代码质量检查结果
type QualityResult struct {
	IsValid     bool     `protobuf:"varint,1,opt,name=is_valid" json:"is_valid,omitempty"`
	Errors      []string `protobuf:"bytes,2,rep,name=errors" json:"errors,omitempty"`
	Suggestions []string `protobuf:"bytes,3,rep,name=suggestions" json:"suggestions,omitempty"`
}

func (x *QualityResult) Reset() { *x = QualityResult{} }

func (x *QualityResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *QualityResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *QualityResult) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *QualityResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *QualityResult) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

// 消息内容
type Message struct {
	Role    string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (x *Message) Reset() { *x = Message{} }

func (x *Message) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Message) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenerateHtmlCodeRequest struct {
	UserMessage string `protobuf:"bytes,1,opt,name=user_message" json:"user_message,omitempty"`
}

func (x *GenerateHtmlCodeRequest) Reset() { *x = GenerateHtmlCodeRequest{} }

func (x *GenerateHtmlCodeRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateHtmlCodeRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GenerateHtmlCodeRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

type GenerateHtmlCodeResponse struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *GenerateHtmlCodeResponse) Reset() { *x = GenerateHtmlCodeResponse{} }

func (x *GenerateHtmlCodeResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateHtmlCodeResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GenerateHtmlCodeResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type GenerateMultiFileCodeRequest struct {
	UserMessage string `protobuf:"bytes,1,opt,name=user_message" json:"user_message,omitempty"`
}

func (x *GenerateMultiFileCodeRequest) Reset() { *x = GenerateMultiFileCodeRequest{} }

func (x *GenerateMultiFileCodeRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateMultiFileCodeRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GenerateMultiFileCodeRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

type GenerateMultiFileCodeResponse struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *GenerateMultiFileCodeResponse) Reset() { *x = GenerateMultiFileCodeResponse{} }

func (x *GenerateMultiFileCodeResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateMultiFileCodeResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GenerateMultiFileCodeResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type GenerateHtmlCodeStreamRequest struct {
	UserMessage string `protobuf:"bytes,1,opt,name=user_message" json:"user_message,omitempty"`
}

func (x *GenerateHtmlCodeStreamRequest) Reset() { *x = GenerateHtmlCodeStreamRequest{} }

func (x *GenerateHtmlCodeStreamRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateHtmlCodeStreamRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GenerateHtmlCodeStreamRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

type GenerateHtmlCodeStreamResponse struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *GenerateHtmlCodeStreamResponse) Reset() { *x = GenerateHtmlCodeStreamResponse{} }

func (x *GenerateHtmlCodeStreamResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateHtmlCodeStreamResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GenerateHtmlCodeStreamResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type GenerateMultiFileCodeStreamRequest struct {
	UserMessage string `protobuf:"bytes,1,opt,name=user_message" json:"user_message,omitempty"`
}

func (x *GenerateMultiFileCodeStreamRequest) Reset() { *x = GenerateMultiFileCodeStreamRequest{} }

func (x *GenerateMultiFileCodeStreamRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateMultiFileCodeStreamRequest) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *GenerateMultiFileCodeStreamRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

type GenerateMultiFileCodeStreamResponse struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *GenerateMultiFileCodeStreamResponse) Reset() { *x = GenerateMultiFileCodeStreamResponse{} }

func (x *GenerateMultiFileCodeStreamResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateMultiFileCodeStreamResponse) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *GenerateMultiFileCodeStreamResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type GenerateVueProjectCodeStreamRequest struct {
	UserMessage string `protobuf:"bytes,1,opt,name=user_message" json:"user_message,omitempty"`
}

func (x *GenerateVueProjectCodeStreamRequest) Reset() { *x = GenerateVueProjectCodeStreamRequest{} }

func (x *GenerateVueProjectCodeStreamRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateVueProjectCodeStreamRequest) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *GenerateVueProjectCodeStreamRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

type GenerateVueProjectCodeStreamResponse struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *GenerateVueProjectCodeStreamResponse) Reset() { *x = GenerateVueProjectCodeStreamResponse{} }

func (x *GenerateVueProjectCodeStreamResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GenerateVueProjectCodeStreamResponse) Unmarshal(in []byte) error {
	return prutal.Unmarshal(in, x)
}

func (x *GenerateVueProjectCodeStreamResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type RouteCodeGenTypeRequest struct {
	UserContent string `protobuf:"bytes,1,opt,name=user_content" json:"user_content,omitempty"`
}

func (x *RouteCodeGenTypeRequest) Reset() { *x = RouteCodeGenTypeRequest{} }

func (x *RouteCodeGenTypeRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RouteCodeGenTypeRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RouteCodeGenTypeRequest) GetUserContent() string {
	if x != nil {
		return x.UserContent
	}
	return ""
}

type RouteCodeGenTypeResponse struct {
	CodeGenType CodeGenType `protobuf:"varint,1,opt,name=code_gen_type" json:"code_gen_type,omitempty"`
}

func (x *RouteCodeGenTypeResponse) Reset() { *x = RouteCodeGenTypeResponse{} }

func (x *RouteCodeGenTypeResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *RouteCodeGenTypeResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RouteCodeGenTypeResponse) GetCodeGenType() CodeGenType {
	if x != nil {
		return x.CodeGenType
	}
	return CodeGenType_HTML
}

type SummarizeChatRequest struct {
	ChatHistory string `protobuf:"bytes,1,opt,name=chat_history" json:"chat_history,omitempty"`
}

func (x *SummarizeChatRequest) Reset() { *x = SummarizeChatRequest{} }

func (x *SummarizeChatRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SummarizeChatRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SummarizeChatRequest) GetChatHistory() string {
	if x != nil {
		return x.ChatHistory
	}
	return ""
}

type SummarizeChatResponse struct {
	Message *Message `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *SummarizeChatResponse) Reset() { *x = SummarizeChatResponse{} }

func (x *SummarizeChatResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SummarizeChatResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SummarizeChatResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type CheckCodeQualityRequest struct {
	UserMessage string `protobuf:"bytes,1,opt,name=user_message" json:"user_message,omitempty"`
}

func (x *CheckCodeQualityRequest) Reset() { *x = CheckCodeQualityRequest{} }

func (x *CheckCodeQualityRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CheckCodeQualityRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckCodeQualityRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

type CheckCodeQualityResponse struct {
	QualityResult *QualityResult `protobuf:"bytes,1,opt,name=quality_result" json:"quality_result,omitempty"`
}

func (x *CheckCodeQualityResponse) Reset() { *x = CheckCodeQualityResponse{} }

func (x *CheckCodeQualityResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CheckCodeQualityResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckCodeQualityResponse) GetQualityResult() *QualityResult {
	if x != nil {
		return x.QualityResult
	}
	return nil
}

type AiService interface {
	GenerateHtmlCode(ctx context.Context, req *GenerateHtmlCodeRequest) (res *GenerateHtmlCodeResponse, err error)
	GenerateMultiFileCode(ctx context.Context, req *GenerateMultiFileCodeRequest) (res *GenerateMultiFileCodeResponse, err error)
	GenerateHtmlCodeStream(req *GenerateHtmlCodeStreamRequest, stream AiService_GenerateHtmlCodeStreamServer) (err error)
	GenerateMultiFileCodeStream(req *GenerateMultiFileCodeStreamRequest, stream AiService_GenerateMultiFileCodeStreamServer) (err error)
	GenerateVueProjectCodeStream(req *GenerateVueProjectCodeStreamRequest, stream AiService_GenerateVueProjectCodeStreamServer) (err error)
	RouteCodeGenType(ctx context.Context, req *RouteCodeGenTypeRequest) (res *RouteCodeGenTypeResponse, err error)
	SummarizeChat(ctx context.Context, req *SummarizeChatRequest) (res *SummarizeChatResponse, err error)
	CheckCodeQuality(ctx context.Context, req *CheckCodeQualityRequest) (res *CheckCodeQualityResponse, err error)
}

type AiService_GenerateHtmlCodeStreamServer interface {
	streaming.Stream
	Send(*GenerateHtmlCodeStreamResponse) error
}

type AiService_GenerateMultiFileCodeStreamServer interface {
	streaming.Stream
	Send(*GenerateMultiFileCodeStreamResponse) error
}

type AiService_GenerateVueProjectCodeStreamServer interface {
	streaming.Stream
	Send(*GenerateVueProjectCodeStreamResponse) error
}
