// Code generated by Kitex v0.16.1. DO NOT EDIT.

package aiservice

import (
	"context"
	"errors"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	kitex_gen "yikou-ai-go-microservice/services/ai/kitex_gen"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenerateHtmlCode": kitex.NewMethodInfo(
		generateHtmlCodeHandler,
		newGenerateHtmlCodeArgs,
		newGenerateHtmlCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GenerateMultiFileCode": kitex.NewMethodInfo(
		generateMultiFileCodeHandler,
		newGenerateMultiFileCodeArgs,
		newGenerateMultiFileCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GenerateHtmlCodeStream": kitex.NewMethodInfo(
		generateHtmlCodeStreamHandler,
		newGenerateHtmlCodeStreamArgs,
		newGenerateHtmlCodeStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"GenerateMultiFileCodeStream": kitex.NewMethodInfo(
		generateMultiFileCodeStreamHandler,
		newGenerateMultiFileCodeStreamArgs,
		newGenerateMultiFileCodeStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"GenerateVueProjectCodeStream": kitex.NewMethodInfo(
		generateVueProjectCodeStreamHandler,
		newGenerateVueProjectCodeStreamArgs,
		newGenerateVueProjectCodeStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"RouteCodeGenType": kitex.NewMethodInfo(
		routeCodeGenTypeHandler,
		newRouteCodeGenTypeArgs,
		newRouteCodeGenTypeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SummarizeChat": kitex.NewMethodInfo(
		summarizeChatHandler,
		newSummarizeChatArgs,
		newSummarizeChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CheckCodeQuality": kitex.NewMethodInfo(
		checkCodeQualityHandler,
		newCheckCodeQualityArgs,
		newCheckCodeQualityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	aiServiceServiceInfo                = NewServiceInfo()
	aiServiceServiceInfoForClient       = NewServiceInfoForClient()
	aiServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aiServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aiServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aiServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AiService"
	handlerType := (*kitex_gen.AiService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "yikou.ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func generateHtmlCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GenerateHtmlCodeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.AiService).GenerateHtmlCode(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenerateHtmlCodeArgs:
		success, err := handler.(kitex_gen.AiService).GenerateHtmlCode(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenerateHtmlCodeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenerateHtmlCodeArgs() interface{} {
	return &GenerateHtmlCodeArgs{}
}

func newGenerateHtmlCodeResult() interface{} {
	return &GenerateHtmlCodeResult{}
}

type GenerateHtmlCodeArgs struct {
	Req *kitex_gen.GenerateHtmlCodeRequest
}

func (p *GenerateHtmlCodeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateHtmlCodeArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateHtmlCodeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateHtmlCodeArgs_Req_DEFAULT *kitex_gen.GenerateHtmlCodeRequest

func (p *GenerateHtmlCodeArgs) GetReq() *kitex_gen.GenerateHtmlCodeRequest {
	if !p.IsSetReq() {
		return GenerateHtmlCodeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateHtmlCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateHtmlCodeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateHtmlCodeResult struct {
	Success *kitex_gen.GenerateHtmlCodeResponse
}

var GenerateHtmlCodeResult_Success_DEFAULT *kitex_gen.GenerateHtmlCodeResponse

func (p *GenerateHtmlCodeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateHtmlCodeResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateHtmlCodeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateHtmlCodeResult) GetSuccess() *kitex_gen.GenerateHtmlCodeResponse {
	if !p.IsSetSuccess() {
		return GenerateHtmlCodeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateHtmlCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GenerateHtmlCodeResponse)
}

func (p *GenerateHtmlCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateHtmlCodeResult) GetResult() interface{} {
	return p.Success
}

func generateMultiFileCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GenerateMultiFileCodeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.AiService).GenerateMultiFileCode(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenerateMultiFileCodeArgs:
		success, err := handler.(kitex_gen.AiService).GenerateMultiFileCode(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenerateMultiFileCodeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenerateMultiFileCodeArgs() interface{} {
	return &GenerateMultiFileCodeArgs{}
}

func newGenerateMultiFileCodeResult() interface{} {
	return &GenerateMultiFileCodeResult{}
}

type GenerateMultiFileCodeArgs struct {
	Req *kitex_gen.GenerateMultiFileCodeRequest
}

func (p *GenerateMultiFileCodeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateMultiFileCodeArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateMultiFileCodeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateMultiFileCodeArgs_Req_DEFAULT *kitex_gen.GenerateMultiFileCodeRequest

func (p *GenerateMultiFileCodeArgs) GetReq() *kitex_gen.GenerateMultiFileCodeRequest {
	if !p.IsSetReq() {
		return GenerateMultiFileCodeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateMultiFileCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateMultiFileCodeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateMultiFileCodeResult struct {
	Success *kitex_gen.GenerateMultiFileCodeResponse
}

var GenerateMultiFileCodeResult_Success_DEFAULT *kitex_gen.GenerateMultiFileCodeResponse

func (p *GenerateMultiFileCodeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateMultiFileCodeResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateMultiFileCodeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateMultiFileCodeResult) GetSuccess() *kitex_gen.GenerateMultiFileCodeResponse {
	if !p.IsSetSuccess() {
		return GenerateMultiFileCodeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateMultiFileCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GenerateMultiFileCodeResponse)
}

func (p *GenerateMultiFileCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateMultiFileCodeResult) GetResult() interface{} {
	return p.Success
}

func generateHtmlCodeStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &aiServiceGenerateHtmlCodeStreamServer{st}
	req := new(kitex_gen.GenerateHtmlCodeStreamRequest)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(kitex_gen.AiService).GenerateHtmlCodeStream(req, stream)
}

type aiServiceGenerateHtmlCodeStreamClient struct {
	streaming.Stream
}

func (x *aiServiceGenerateHtmlCodeStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *aiServiceGenerateHtmlCodeStreamClient) Recv() (*kitex_gen.GenerateHtmlCodeStreamResponse, error) {
	m := new(kitex_gen.GenerateHtmlCodeStreamResponse)
	return m, x.Stream.RecvMsg(m)
}

type aiServiceGenerateHtmlCodeStreamServer struct {
	streaming.Stream
}

func (x *aiServiceGenerateHtmlCodeStreamServer) Send(m *kitex_gen.GenerateHtmlCodeStreamResponse) error {
	return x.Stream.SendMsg(m)
}

func newGenerateHtmlCodeStreamArgs() interface{} {
	return &GenerateHtmlCodeStreamArgs{}
}

func newGenerateHtmlCodeStreamResult() interface{} {
	return &GenerateHtmlCodeStreamResult{}
}

type GenerateHtmlCodeStreamArgs struct {
	Req *kitex_gen.GenerateHtmlCodeStreamRequest
}

func (p *GenerateHtmlCodeStreamArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateHtmlCodeStreamArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateHtmlCodeStreamRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateHtmlCodeStreamArgs_Req_DEFAULT *kitex_gen.GenerateHtmlCodeStreamRequest

func (p *GenerateHtmlCodeStreamArgs) GetReq() *kitex_gen.GenerateHtmlCodeStreamRequest {
	if !p.IsSetReq() {
		return GenerateHtmlCodeStreamArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateHtmlCodeStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateHtmlCodeStreamArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateHtmlCodeStreamResult struct {
	Success *kitex_gen.GenerateHtmlCodeStreamResponse
}

var GenerateHtmlCodeStreamResult_Success_DEFAULT *kitex_gen.GenerateHtmlCodeStreamResponse

func (p *GenerateHtmlCodeStreamResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateHtmlCodeStreamResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateHtmlCodeStreamResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateHtmlCodeStreamResult) GetSuccess() *kitex_gen.GenerateHtmlCodeStreamResponse {
	if !p.IsSetSuccess() {
		return GenerateHtmlCodeStreamResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateHtmlCodeStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GenerateHtmlCodeStreamResponse)
}

func (p *GenerateHtmlCodeStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateHtmlCodeStreamResult) GetResult() interface{} {
	return p.Success
}

func generateMultiFileCodeStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &aiServiceGenerateMultiFileCodeStreamServer{st}
	req := new(kitex_gen.GenerateMultiFileCodeStreamRequest)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(kitex_gen.AiService).GenerateMultiFileCodeStream(req, stream)
}

type aiServiceGenerateMultiFileCodeStreamClient struct {
	streaming.Stream
}

func (x *aiServiceGenerateMultiFileCodeStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *aiServiceGenerateMultiFileCodeStreamClient) Recv() (*kitex_gen.GenerateMultiFileCodeStreamResponse, error) {
	m := new(kitex_gen.GenerateMultiFileCodeStreamResponse)
	return m, x.Stream.RecvMsg(m)
}

type aiServiceGenerateMultiFileCodeStreamServer struct {
	streaming.Stream
}

func (x *aiServiceGenerateMultiFileCodeStreamServer) Send(m *kitex_gen.GenerateMultiFileCodeStreamResponse) error {
	return x.Stream.SendMsg(m)
}

func newGenerateMultiFileCodeStreamArgs() interface{} {
	return &GenerateMultiFileCodeStreamArgs{}
}

func newGenerateMultiFileCodeStreamResult() interface{} {
	return &GenerateMultiFileCodeStreamResult{}
}

type GenerateMultiFileCodeStreamArgs struct {
	Req *kitex_gen.GenerateMultiFileCodeStreamRequest
}

func (p *GenerateMultiFileCodeStreamArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateMultiFileCodeStreamArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateMultiFileCodeStreamRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateMultiFileCodeStreamArgs_Req_DEFAULT *kitex_gen.GenerateMultiFileCodeStreamRequest

func (p *GenerateMultiFileCodeStreamArgs) GetReq() *kitex_gen.GenerateMultiFileCodeStreamRequest {
	if !p.IsSetReq() {
		return GenerateMultiFileCodeStreamArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateMultiFileCodeStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateMultiFileCodeStreamArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateMultiFileCodeStreamResult struct {
	Success *kitex_gen.GenerateMultiFileCodeStreamResponse
}

var GenerateMultiFileCodeStreamResult_Success_DEFAULT *kitex_gen.GenerateMultiFileCodeStreamResponse

func (p *GenerateMultiFileCodeStreamResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateMultiFileCodeStreamResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateMultiFileCodeStreamResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateMultiFileCodeStreamResult) GetSuccess() *kitex_gen.GenerateMultiFileCodeStreamResponse {
	if !p.IsSetSuccess() {
		return GenerateMultiFileCodeStreamResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateMultiFileCodeStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GenerateMultiFileCodeStreamResponse)
}

func (p *GenerateMultiFileCodeStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateMultiFileCodeStreamResult) GetResult() interface{} {
	return p.Success
}

func generateVueProjectCodeStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &aiServiceGenerateVueProjectCodeStreamServer{st}
	req := new(kitex_gen.GenerateVueProjectCodeStreamRequest)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(kitex_gen.AiService).GenerateVueProjectCodeStream(req, stream)
}

type aiServiceGenerateVueProjectCodeStreamClient struct {
	streaming.Stream
}

func (x *aiServiceGenerateVueProjectCodeStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *aiServiceGenerateVueProjectCodeStreamClient) Recv() (*kitex_gen.GenerateVueProjectCodeStreamResponse, error) {
	m := new(kitex_gen.GenerateVueProjectCodeStreamResponse)
	return m, x.Stream.RecvMsg(m)
}

type aiServiceGenerateVueProjectCodeStreamServer struct {
	streaming.Stream
}

func (x *aiServiceGenerateVueProjectCodeStreamServer) Send(m *kitex_gen.GenerateVueProjectCodeStreamResponse) error {
	return x.Stream.SendMsg(m)
}

func newGenerateVueProjectCodeStreamArgs() interface{} {
	return &GenerateVueProjectCodeStreamArgs{}
}

func newGenerateVueProjectCodeStreamResult() interface{} {
	return &GenerateVueProjectCodeStreamResult{}
}

type GenerateVueProjectCodeStreamArgs struct {
	Req *kitex_gen.GenerateVueProjectCodeStreamRequest
}

func (p *GenerateVueProjectCodeStreamArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateVueProjectCodeStreamArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateVueProjectCodeStreamRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateVueProjectCodeStreamArgs_Req_DEFAULT *kitex_gen.GenerateVueProjectCodeStreamRequest

func (p *GenerateVueProjectCodeStreamArgs) GetReq() *kitex_gen.GenerateVueProjectCodeStreamRequest {
	if !p.IsSetReq() {
		return GenerateVueProjectCodeStreamArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateVueProjectCodeStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateVueProjectCodeStreamArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateVueProjectCodeStreamResult struct {
	Success *kitex_gen.GenerateVueProjectCodeStreamResponse
}

var GenerateVueProjectCodeStreamResult_Success_DEFAULT *kitex_gen.GenerateVueProjectCodeStreamResponse

func (p *GenerateVueProjectCodeStreamResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateVueProjectCodeStreamResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateVueProjectCodeStreamResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateVueProjectCodeStreamResult) GetSuccess() *kitex_gen.GenerateVueProjectCodeStreamResponse {
	if !p.IsSetSuccess() {
		return GenerateVueProjectCodeStreamResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateVueProjectCodeStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GenerateVueProjectCodeStreamResponse)
}

func (p *GenerateVueProjectCodeStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateVueProjectCodeStreamResult) GetResult() interface{} {
	return p.Success
}

func routeCodeGenTypeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.RouteCodeGenTypeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.AiService).RouteCodeGenType(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RouteCodeGenTypeArgs:
		success, err := handler.(kitex_gen.AiService).RouteCodeGenType(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RouteCodeGenTypeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRouteCodeGenTypeArgs() interface{} {
	return &RouteCodeGenTypeArgs{}
}

func newRouteCodeGenTypeResult() interface{} {
	return &RouteCodeGenTypeResult{}
}

type RouteCodeGenTypeArgs struct {
	Req *kitex_gen.RouteCodeGenTypeRequest
}

func (p *RouteCodeGenTypeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RouteCodeGenTypeArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.RouteCodeGenTypeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RouteCodeGenTypeArgs_Req_DEFAULT *kitex_gen.RouteCodeGenTypeRequest

func (p *RouteCodeGenTypeArgs) GetReq() *kitex_gen.RouteCodeGenTypeRequest {
	if !p.IsSetReq() {
		return RouteCodeGenTypeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RouteCodeGenTypeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RouteCodeGenTypeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RouteCodeGenTypeResult struct {
	Success *kitex_gen.RouteCodeGenTypeResponse
}

var RouteCodeGenTypeResult_Success_DEFAULT *kitex_gen.RouteCodeGenTypeResponse

func (p *RouteCodeGenTypeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RouteCodeGenTypeResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.RouteCodeGenTypeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RouteCodeGenTypeResult) GetSuccess() *kitex_gen.RouteCodeGenTypeResponse {
	if !p.IsSetSuccess() {
		return RouteCodeGenTypeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RouteCodeGenTypeResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.RouteCodeGenTypeResponse)
}

func (p *RouteCodeGenTypeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RouteCodeGenTypeResult) GetResult() interface{} {
	return p.Success
}

func summarizeChatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.SummarizeChatRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.AiService).SummarizeChat(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SummarizeChatArgs:
		success, err := handler.(kitex_gen.AiService).SummarizeChat(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SummarizeChatResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSummarizeChatArgs() interface{} {
	return &SummarizeChatArgs{}
}

func newSummarizeChatResult() interface{} {
	return &SummarizeChatResult{}
}

type SummarizeChatArgs struct {
	Req *kitex_gen.SummarizeChatRequest
}

func (p *SummarizeChatArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SummarizeChatArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.SummarizeChatRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SummarizeChatArgs_Req_DEFAULT *kitex_gen.SummarizeChatRequest

func (p *SummarizeChatArgs) GetReq() *kitex_gen.SummarizeChatRequest {
	if !p.IsSetReq() {
		return SummarizeChatArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SummarizeChatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SummarizeChatArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SummarizeChatResult struct {
	Success *kitex_gen.SummarizeChatResponse
}

var SummarizeChatResult_Success_DEFAULT *kitex_gen.SummarizeChatResponse

func (p *SummarizeChatResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SummarizeChatResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.SummarizeChatResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SummarizeChatResult) GetSuccess() *kitex_gen.SummarizeChatResponse {
	if !p.IsSetSuccess() {
		return SummarizeChatResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SummarizeChatResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.SummarizeChatResponse)
}

func (p *SummarizeChatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SummarizeChatResult) GetResult() interface{} {
	return p.Success
}

func checkCodeQualityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.CheckCodeQualityRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.AiService).CheckCodeQuality(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckCodeQualityArgs:
		success, err := handler.(kitex_gen.AiService).CheckCodeQuality(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckCodeQualityResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckCodeQualityArgs() interface{} {
	return &CheckCodeQualityArgs{}
}

func newCheckCodeQualityResult() interface{} {
	return &CheckCodeQualityResult{}
}

type CheckCodeQualityArgs struct {
	Req *kitex_gen.CheckCodeQualityRequest
}

func (p *CheckCodeQualityArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckCodeQualityArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.CheckCodeQualityRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckCodeQualityArgs_Req_DEFAULT *kitex_gen.CheckCodeQualityRequest

func (p *CheckCodeQualityArgs) GetReq() *kitex_gen.CheckCodeQualityRequest {
	if !p.IsSetReq() {
		return CheckCodeQualityArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckCodeQualityArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckCodeQualityArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckCodeQualityResult struct {
	Success *kitex_gen.CheckCodeQualityResponse
}

var CheckCodeQualityResult_Success_DEFAULT *kitex_gen.CheckCodeQualityResponse

func (p *CheckCodeQualityResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckCodeQualityResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.CheckCodeQualityResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckCodeQualityResult) GetSuccess() *kitex_gen.CheckCodeQualityResponse {
	if !p.IsSetSuccess() {
		return CheckCodeQualityResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckCodeQualityResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.CheckCodeQualityResponse)
}

func (p *CheckCodeQualityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckCodeQualityResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenerateHtmlCode(ctx context.Context, Req *kitex_gen.GenerateHtmlCodeRequest) (r *kitex_gen.GenerateHtmlCodeResponse, err error) {
	var _args GenerateHtmlCodeArgs
	_args.Req = Req
	var _result GenerateHtmlCodeResult
	if err = p.c.Call(ctx, "GenerateHtmlCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GenerateMultiFileCode(ctx context.Context, Req *kitex_gen.GenerateMultiFileCodeRequest) (r *kitex_gen.GenerateMultiFileCodeResponse, err error) {
	var _args GenerateMultiFileCodeArgs
	_args.Req = Req
	var _result GenerateMultiFileCodeResult
	if err = p.c.Call(ctx, "GenerateMultiFileCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GenerateHtmlCodeStream(ctx context.Context, req *kitex_gen.GenerateHtmlCodeStreamRequest) (AiService_GenerateHtmlCodeStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "GenerateHtmlCodeStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &aiServiceGenerateHtmlCodeStreamClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) GenerateMultiFileCodeStream(ctx context.Context, req *kitex_gen.GenerateMultiFileCodeStreamRequest) (AiService_GenerateMultiFileCodeStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "GenerateMultiFileCodeStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &aiServiceGenerateMultiFileCodeStreamClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) GenerateVueProjectCodeStream(ctx context.Context, req *kitex_gen.GenerateVueProjectCodeStreamRequest) (AiService_GenerateVueProjectCodeStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "GenerateVueProjectCodeStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &aiServiceGenerateVueProjectCodeStreamClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) RouteCodeGenType(ctx context.Context, Req *kitex_gen.RouteCodeGenTypeRequest) (r *kitex_gen.RouteCodeGenTypeResponse, err error) {
	var _args RouteCodeGenTypeArgs
	_args.Req = Req
	var _result RouteCodeGenTypeResult
	if err = p.c.Call(ctx, "RouteCodeGenType", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SummarizeChat(ctx context.Context, Req *kitex_gen.SummarizeChatRequest) (r *kitex_gen.SummarizeChatResponse, err error) {
	var _args SummarizeChatArgs
	_args.Req = Req
	var _result SummarizeChatResult
	if err = p.c.Call(ctx, "SummarizeChat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckCodeQuality(ctx context.Context, Req *kitex_gen.CheckCodeQualityRequest) (r *kitex_gen.CheckCodeQualityResponse, err error) {
	var _args CheckCodeQualityArgs
	_args.Req = Req
	var _result CheckCodeQualityResult
	if err = p.c.Call(ctx, "CheckCodeQuality", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
