// Code generated by Kitex v0.16.1. DO NOT EDIT.

package aiservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streamclient "github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	kitex_gen "yikou-ai-go-microservice/services/ai/kitex_gen"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenerateHtmlCode(ctx context.Context, Req *kitex_gen.GenerateHtmlCodeRequest, callOptions ...callopt.Option) (r *kitex_gen.GenerateHtmlCodeResponse, err error)
	GenerateMultiFileCode(ctx context.Context, Req *kitex_gen.GenerateMultiFileCodeRequest, callOptions ...callopt.Option) (r *kitex_gen.GenerateMultiFileCodeResponse, err error)
	GenerateHtmlCodeStream(ctx context.Context, Req *kitex_gen.GenerateHtmlCodeStreamRequest, callOptions ...callopt.Option) (stream AiService_GenerateHtmlCodeStreamClient, err error)
	GenerateMultiFileCodeStream(ctx context.Context, Req *kitex_gen.GenerateMultiFileCodeStreamRequest, callOptions ...callopt.Option) (stream AiService_GenerateMultiFileCodeStreamClient, err error)
	GenerateVueProjectCodeStream(ctx context.Context, Req *kitex_gen.GenerateVueProjectCodeStreamRequest, callOptions ...callopt.Option) (stream AiService_GenerateVueProjectCodeStreamClient, err error)
	RouteCodeGenType(ctx context.Context, Req *kitex_gen.RouteCodeGenTypeRequest, callOptions ...callopt.Option) (r *kitex_gen.RouteCodeGenTypeResponse, err error)
	SummarizeChat(ctx context.Context, Req *kitex_gen.SummarizeChatRequest, callOptions ...callopt.Option) (r *kitex_gen.SummarizeChatResponse, err error)
	CheckCodeQuality(ctx context.Context, Req *kitex_gen.CheckCodeQualityRequest, callOptions ...callopt.Option) (r *kitex_gen.CheckCodeQualityResponse, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	GenerateHtmlCodeStream(ctx context.Context, Req *kitex_gen.GenerateHtmlCodeStreamRequest, callOptions ...streamcall.Option) (stream AiService_GenerateHtmlCodeStreamClient, err error)
	GenerateMultiFileCodeStream(ctx context.Context, Req *kitex_gen.GenerateMultiFileCodeStreamRequest, callOptions ...streamcall.Option) (stream AiService_GenerateMultiFileCodeStreamClient, err error)
	GenerateVueProjectCodeStream(ctx context.Context, Req *kitex_gen.GenerateVueProjectCodeStreamRequest, callOptions ...streamcall.Option) (stream AiService_GenerateVueProjectCodeStreamClient, err error)
}

type AiService_GenerateHtmlCodeStreamClient interface {
	streaming.Stream
	Recv() (*kitex_gen.GenerateHtmlCodeStreamResponse, error)
}

type AiService_GenerateMultiFileCodeStreamClient interface {
	streaming.Stream
	Recv() (*kitex_gen.GenerateMultiFileCodeStreamResponse, error)
}

type AiService_GenerateVueProjectCodeStreamClient interface {
	streaming.Stream
	Recv() (*kitex_gen.GenerateVueProjectCodeStreamResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAiServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAiServiceClient struct {
	*kClient
}

func (p *kAiServiceClient) GenerateHtmlCode(ctx context.Context, Req *kitex_gen.GenerateHtmlCodeRequest, callOptions ...callopt.Option) (r *kitex_gen.GenerateHtmlCodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateHtmlCode(ctx, Req)
}

func (p *kAiServiceClient) GenerateMultiFileCode(ctx context.Context, Req *kitex_gen.GenerateMultiFileCodeRequest, callOptions ...callopt.Option) (r *kitex_gen.GenerateMultiFileCodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateMultiFileCode(ctx, Req)
}

func (p *kAiServiceClient) GenerateHtmlCodeStream(ctx context.Context, Req *kitex_gen.GenerateHtmlCodeStreamRequest, callOptions ...callopt.Option) (stream AiService_GenerateHtmlCodeStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateHtmlCodeStream(ctx, Req)
}

func (p *kAiServiceClient) GenerateMultiFileCodeStream(ctx context.Context, Req *kitex_gen.GenerateMultiFileCodeStreamRequest, callOptions ...callopt.Option) (stream AiService_GenerateMultiFileCodeStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateMultiFileCodeStream(ctx, Req)
}

func (p *kAiServiceClient) GenerateVueProjectCodeStream(ctx context.Context, Req *kitex_gen.GenerateVueProjectCodeStreamRequest, callOptions ...callopt.Option) (stream AiService_GenerateVueProjectCodeStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateVueProjectCodeStream(ctx, Req)
}

func (p *kAiServiceClient) RouteCodeGenType(ctx context.Context, Req *kitex_gen.RouteCodeGenTypeRequest, callOptions ...callopt.Option) (r *kitex_gen.RouteCodeGenTypeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RouteCodeGenType(ctx, Req)
}

func (p *kAiServiceClient) SummarizeChat(ctx context.Context, Req *kitex_gen.SummarizeChatRequest, callOptions ...callopt.Option) (r *kitex_gen.SummarizeChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SummarizeChat(ctx, Req)
}

func (p *kAiServiceClient) CheckCodeQuality(ctx context.Context, Req *kitex_gen.CheckCodeQualityRequest, callOptions ...callopt.Option) (r *kitex_gen.CheckCodeQualityResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckCodeQuality(ctx, Req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAiServiceStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAiServiceStreamClient struct {
	*kClient
}

func (p *kAiServiceStreamClient) GenerateHtmlCodeStream(ctx context.Context, Req *kitex_gen.GenerateHtmlCodeStreamRequest, callOptions ...streamcall.Option) (stream AiService_GenerateHtmlCodeStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.GenerateHtmlCodeStream(ctx, Req)
}

func (p *kAiServiceStreamClient) GenerateMultiFileCodeStream(ctx context.Context, Req *kitex_gen.GenerateMultiFileCodeStreamRequest, callOptions ...streamcall.Option) (stream AiService_GenerateMultiFileCodeStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.GenerateMultiFileCodeStream(ctx, Req)
}

func (p *kAiServiceStreamClient) GenerateVueProjectCodeStream(ctx context.Context, Req *kitex_gen.GenerateVueProjectCodeStreamRequest, callOptions ...streamcall.Option) (stream AiService_GenerateVueProjectCodeStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.GenerateVueProjectCodeStream(ctx, Req)
}
