// Code generated by Kitex v0.16.1. DO NOT EDIT.
package aiservice

import (
	server "github.com/cloudwego/kitex/server"
	kitex_gen "yikou-ai-go-microservice/services/ai/kitex_gen"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kitex_gen.AiService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler kitex_gen.AiService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
