// Code generated by hertz generator.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	enum "yikou-ai-go-microservice/pkg/commonenum"
	"yikou-ai-go-microservice/pkg/commonmiddleware"
	"yikou-ai-go-microservice/services/user/handler"
)

// CustomizedRegister registers customize routers.
func CustomizedRegister(r *server.Hertz, db *gorm.DB, redisClient *redis.Client, userHandler *handler.UserHandler) {

	userRoute := r.Group("/user")
	{
		userRoute.POST("/register", userHandler.UserRegister)
		userRoute.POST("/login", userHandler.UserLogin)
		userRoute.GET("/get/vo", userHandler.GetUserVo)

		// 需要登录的接口
		userRoute.GET("/get/login", commonmiddleware.AuthMiddleware(enum.UserRole, db, redisClient), userHandler.GetLoginUser)
		userRoute.POST("/logout", commonmiddleware.AuthMiddleware(enum.UserRole, db, redisClient), userHandler.Logout)

		userRoute.POST("/add", commonmiddleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.AddUser)
		userRoute.GET("/get", commonmiddleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.GetUser)
		userRoute.POST("/delete", commonmiddleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.DeleteUser)
		userRoute.POST("/update", commonmiddleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.UpdateUser)
		userRoute.POST("/list/page/vo", commonmiddleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.ListUserVoByPage)
	}
}
