// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"fmt"
	"github.com/bytedance/gopkg/util/logger"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/google/wire"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/swagger"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"strconv"
	"time"
	"workspace-yikou-ai-go/biz/ai"
	"workspace-yikou-ai-go/biz/ai/agent"
	"workspace-yikou-ai-go/biz/ai/aitools"
	"workspace-yikou-ai-go/biz/ai/llm"
	"workspace-yikou-ai-go/biz/cache"
	"workspace-yikou-ai-go/biz/core"
	"workspace-yikou-ai-go/biz/core/messagehandler"
	"workspace-yikou-ai-go/biz/core/parser"
	"workspace-yikou-ai-go/biz/core/saver"
	"workspace-yikou-ai-go/biz/dal"
	"workspace-yikou-ai-go/biz/graph/node"
	"workspace-yikou-ai-go/biz/handler/app"
	chathistory2 "workspace-yikou-ai-go/biz/handler/chathistory"
	"workspace-yikou-ai-go/biz/handler/static"
	handler2 "workspace-yikou-ai-go/biz/handler/user"
	handler3 "workspace-yikou-ai-go/biz/handler/workflow"
	"workspace-yikou-ai-go/biz/manager"
	"workspace-yikou-ai-go/biz/model/api/common"
	"workspace-yikou-ai-go/biz/router"
	service2 "workspace-yikou-ai-go/biz/service/app"
	"workspace-yikou-ai-go/biz/service/chathistory"
	"workspace-yikou-ai-go/biz/service/download"
	"workspace-yikou-ai-go/biz/service/screenshot"
	"workspace-yikou-ai-go/biz/service/user"
	"workspace-yikou-ai-go/config"
	"workspace-yikou-ai-go/docs"
	"workspace-yikou-ai-go/pkg/errors"
)

// Injectors from wire.go:

// 初始化所有依赖（依赖图）
func InitializeApp() (*server.Hertz, error) {
	configConfig := config.InitConfig()
	chatModel := llm.NewChatModel(configConfig)
	yiKouAiCodegenService := ai.NewYiKouAiCodegenService(chatModel)
	codeParserExecutor := parser.NewCodeParserExecutor()
	codeFileSaverExecutor := saver.NewCodeFileSaverExecutor()
	baseAiChatModel := llm.NewBaseAiChatModel(configConfig)
	reasoningChatModel := llm.NewReasoningChatModel(configConfig)
	client := dal.InitRedis(configConfig)
	db := dal.InitDB(configConfig)
	chatHistoryService := chathistory.NewChatHistoryService(db)
	toolManager, err := aitools.NewToolManager()
	if err != nil {
		return nil, err
	}
	codeGenAgentFactory := agent.NewCodeGenAgentFactory(baseAiChatModel, reasoningChatModel, client, chatHistoryService, toolManager)
	yiKouAiCodegenFacade := core.NewYiKouAiCodegenFacade(yiKouAiCodegenService, codeParserExecutor, codeFileSaverExecutor, codeGenAgentFactory)
	userService := service.NewUserService(db, client)
	streamHandlerExecutor := messagehandler.NewStreamHandlerExecutor(chatHistoryService, toolManager)
	cosClient := dal.InitCOSClient(configConfig)
	cosManager := manager.NewCosManager(cosClient, configConfig)
	screenshotService := screenshot.NewScreenshotService(cosManager)
	codeGenTypeRoutingAgentFactory := agent.NewCodeGenTypeRoutingAgentFactory(baseAiChatModel)
	appService := service2.NewAppService(yiKouAiCodegenFacade, userService, chatHistoryService, streamHandlerExecutor, screenshotService, codeGenTypeRoutingAgentFactory, db)
	projectDownloadService := download.NewProjectDownloadService()
	appHandler := handler.NewAppHandler(appService, userService, chatHistoryService, projectDownloadService)
	userHandler := handler2.NewUserHandler(userService)
	chatHistoryHandler := chathistory2.NewChatHistoryHandler(chatHistoryService, userService)
	staticResourceHandler := static.NewStaticResourceHandler(configConfig)
	workflowHandler := handler3.NewWorkflowHandler()
	cacheManager := cache.InitCacheManager(client)
	nodeInitializer := InitAllNodes(configConfig, baseAiChatModel, cosManager, yiKouAiCodegenFacade)
	hertz := InitServer(configConfig, appHandler, userHandler, chatHistoryHandler, staticResourceHandler, workflowHandler, cacheManager, db, client, userService, nodeInitializer)
	return hertz, nil
}

// wire.go:

// 配置依赖
var configSet = wire.NewSet(config.InitConfig)

// 数据库依赖
var dbSet = wire.NewSet(dal.InitDB, dal.InitRedis, dal.InitCOSClient)

// 缓存依赖
var cacheSet = wire.NewSet(cache.InitCacheManager)

// Service依赖
var serviceSet = wire.NewSet(core.NewYiKouAiCodegenFacade, service2.NewAppService, wire.Bind(new(service2.IAppService), new(*service2.AppService)), service.NewUserService, wire.Bind(new(service.IUserService), new(*service.UserService)), chathistory.NewChatHistoryService, wire.Bind(new(chathistory.IChatHistoryService), new(*chathistory.ChatHistoryService)), screenshot.NewScreenshotService, wire.Bind(new(screenshot.IScreenshotService), new(*screenshot.ScreenshotService)), download.NewProjectDownloadService, wire.Bind(new(download.IProjectDownloadService), new(*download.ProjectDownloadService)))

// Handler依赖
var handlerSet = wire.NewSet(handler.NewAppHandler, handler2.NewUserHandler, chathistory2.NewChatHistoryHandler, static.NewStaticResourceHandler, handler3.NewWorkflowHandler)

var llmSet = wire.NewSet(llm.NewBaseAiChatModel, llm.NewReasoningChatModel, llm.NewChatModel)

type NodeInitializer struct{}

func InitAllNodes(
	cfg *config.Config,
	chatModel *llm.BaseAiChatModel,
	cosManager *manager.CosManager,
	facade *core.YiKouAiCodegenFacade,
) *NodeInitializer {
	node.InitImagePlanNode(chatModel)
	node.InitImageCollectorPlanNode(chatModel, cfg, cosManager)
	node.InitContentImageCollectorNode(cfg)
	node.InitDiagramCollectorNode(cosManager)
	node.InitLogoCollectorNode(cfg, cosManager)
	node.InitRouterNode(chatModel)
	node.InitCodeQualityCheckNode(cfg, chatModel)
	node.InitCodeGeneratorNode(facade)
	node.InitImageCollectorNode(cfg, chatModel)
	return &NodeInitializer{}
}

func CustomRecoveryHandler(ctx context.Context, c *app.RequestContext, err interface{}, stack []byte) {
	logger.Errorf("panic recovered: %v\n%s", err, stack)
	c.JSON(consts.StatusOK, common.NewErrorResponse[any](pkg.SystemError.WithMessage(fmt.Sprintf("%v", err))))
	c.Abort()
}

// Server依赖
func InitServer(
	serverConfig *config.Config,
	appHandler *handler.AppHandler,
	userHandler *handler2.UserHandler,
	chatHistoryHandler *chathistory2.ChatHistoryHandler,
	staticResourceHandler *static.StaticResourceHandler,
	workflowHandler *handler3.WorkflowHandler,
	cacheManager *cache.CacheManager,
	db *gorm.DB,
	redisClient *redis.Client,
	userService service.IUserService,
	_ *NodeInitializer,
) *server.Hertz {
	basePath := serverConfig.Server.ContextPath
	docs.SwaggerInfo.
		BasePath = basePath

	swaggerPath := fmt.Sprintf("http://localhost:%d%s/swagger/doc.json", serverConfig.Server.Port, basePath)
	url := swagger.URL(swaggerPath)
	h := server.New(server.WithHostPorts(":"+strconv.Itoa(serverConfig.Server.Port)), server.WithBasePath(serverConfig.Server.ContextPath))

	h.Use(recovery.Recovery(recovery.WithRecoveryHandler(CustomRecoveryHandler)))

	h.Use(cors.New(cors.Config{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: false,
		MaxAge:           12 * time.Hour,
	}))
	router.CustomizedRegister(h, db, redisClient, appHandler, userHandler, chatHistoryHandler, staticResourceHandler, workflowHandler, cacheManager, userService, url)
	return h
}
