// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/google/wire"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/swagger"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"strconv"
	"time"
	"workspace-yikou-ai-go/biz/ai/agent"
	"workspace-yikou-ai-go/biz/ai/core"
	"workspace-yikou-ai-go/biz/ai/core/parser"
	"workspace-yikou-ai-go/biz/ai/core/saver"
	"workspace-yikou-ai-go/biz/ai/llm"
	"workspace-yikou-ai-go/biz/ai/skill"
	"workspace-yikou-ai-go/biz/ai/store"
	"workspace-yikou-ai-go/biz/dal"
	"workspace-yikou-ai-go/biz/handler/app"
	chathistory2 "workspace-yikou-ai-go/biz/handler/chathistory"
	"workspace-yikou-ai-go/biz/handler/static"
	handler2 "workspace-yikou-ai-go/biz/handler/user"
	"workspace-yikou-ai-go/biz/model/api/common"
	"workspace-yikou-ai-go/biz/router"
	service2 "workspace-yikou-ai-go/biz/service/app"
	"workspace-yikou-ai-go/biz/service/chathistory"
	"workspace-yikou-ai-go/biz/service/user"
	"workspace-yikou-ai-go/config"
	"workspace-yikou-ai-go/docs"
	"workspace-yikou-ai-go/pkg/errors"
)

// Injectors from wire.go:

// 初始化所有依赖（依赖图）
func InitializeApp() (*server.Hertz, error) {
	configConfig := config.InitConfig()
	chatModel := llm.NewChatModel(configConfig)
	yiKouAiCodegenService := skill.NewYiKouAiCodegenService(chatModel)
	codeParserExecutor := parser.NewCodeParserExecutor()
	codeFileSaverExecutor := saver.NewCodeFileSaverExecutor()
	baseAiChatModel := llm.NewBaseAiChatModel(configConfig)
	client := dal.InitRedis(configConfig)
	redisStore := store.NewRedisStore(client)
	codeGenAgentFactory := agent.NewCodeGenAgentFactory(baseAiChatModel, redisStore)
	yiKouAiCodegenFacade := core.NewYiKouAiCodegenFacade(yiKouAiCodegenService, codeParserExecutor, codeFileSaverExecutor, codeGenAgentFactory)
	db := dal.InitDB(configConfig)
	userService := service.NewUserService(db)
	chatHistoryService := chathistory.NewChatHistoryService(db)
	appService := service2.NewAppService(yiKouAiCodegenFacade, userService, chatHistoryService, db)
	appHandler := handler.NewAppHandler(appService, userService, chatHistoryService)
	userHandler := handler2.NewUserHandler(userService)
	chatHistoryHandler := chathistory2.NewChatHistoryHandler(chatHistoryService, userService)
	staticResourceHandler := static.NewStaticResourceHandler(configConfig)
	hertz := InitServer(configConfig, appHandler, userHandler, chatHistoryHandler, staticResourceHandler, db, client)
	return hertz, nil
}

// wire.go:

// 配置依赖
var configSet = wire.NewSet(config.InitConfig)

// 数据库依赖
var dbSet = wire.NewSet(dal.InitDB, dal.InitRedis)

// Service依赖
var serviceSet = wire.NewSet(core.NewYiKouAiCodegenFacade, service2.NewAppService, wire.Bind(new(service2.IAppService), new(*service2.AppService)), service.NewUserService, wire.Bind(new(service.IUserService), new(*service.UserService)), chathistory.NewChatHistoryService, wire.Bind(new(chathistory.IChatHistoryService), new(*chathistory.ChatHistoryService)))

// Handler依赖
var handlerSet = wire.NewSet(handler.NewAppHandler, handler2.NewUserHandler, chathistory2.NewChatHistoryHandler, static.NewStaticResourceHandler)

func CustomRecoveryHandler(ctx context.Context, c *app.RequestContext, err interface{}, stack []byte) {
	c.JSON(consts.StatusOK, common.NewErrorResponse[any](pkg.SystemError.WithMessage(fmt.Sprintf("%v", err))))
	c.Abort()
}

// Server依赖
func InitServer(
	serverConfig *config.Config,
	appHandler *handler.AppHandler,
	userHandler *handler2.UserHandler,
	chatHistoryHandler *chathistory2.ChatHistoryHandler,
	staticResourceHandler *static.StaticResourceHandler,
	db *gorm.DB,
	redisClient *redis.Client,
) *server.Hertz {
	basePath := serverConfig.Server.ContextPath
	docs.SwaggerInfo.
		BasePath = basePath

	swaggerPath := fmt.Sprintf("http://localhost:%d%s/swagger/doc.json", serverConfig.Server.Port, basePath)
	url := swagger.URL(swaggerPath)
	h := server.New(server.WithHostPorts(":"+strconv.Itoa(serverConfig.Server.Port)), server.WithBasePath(serverConfig.Server.ContextPath))

	h.Use(recovery.Recovery(recovery.WithRecoveryHandler(CustomRecoveryHandler)))

	h.Use(cors.New(cors.Config{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: false,
		MaxAge:           12 * time.Hour,
	}))
	router.CustomizedRegister(h, db, appHandler, userHandler, chatHistoryHandler, staticResourceHandler, url)
	return h
}
