// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/google/wire"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/swagger"
	"gorm.io/gorm"
	"strconv"
	"time"
	"workspace-yikou-ai-go/biz/ai/agent"
	"workspace-yikou-ai-go/biz/ai/core"
	"workspace-yikou-ai-go/biz/ai/core/parser"
	"workspace-yikou-ai-go/biz/ai/core/saver"
	"workspace-yikou-ai-go/biz/ai/skill"
	"workspace-yikou-ai-go/biz/dal"
	"workspace-yikou-ai-go/biz/handler/app"
	"workspace-yikou-ai-go/biz/handler/static"
	handler2 "workspace-yikou-ai-go/biz/handler/user"
	"workspace-yikou-ai-go/biz/router"
	service2 "workspace-yikou-ai-go/biz/service/app"
	"workspace-yikou-ai-go/biz/service/chat_history"
	"workspace-yikou-ai-go/biz/service/user"
	"workspace-yikou-ai-go/config"
	"workspace-yikou-ai-go/docs"
)

// Injectors from wire.go:

// 初始化所有依赖（依赖图）
func InitializeApp() (*server.Hertz, error) {
	configConfig := config.InitConfig()
	chatModel := agent.NewChatAgent(configConfig)
	yiKouAiCodegenService := skill.NewYiKouAiCodegenService(chatModel)
	codeParserExecutor := parser.NewCodeParserExecutor()
	codeFileSaverExecutor := saver.NewCodeFileSaverExecutor()
	yiKouAiCodegenFacade := core.NewYiKouAiCodegenFacade(yiKouAiCodegenService, codeParserExecutor, codeFileSaverExecutor)
	db := dal.InitDB(configConfig)
	userService := service.NewUserService(db)
	chatHistoryService := chat_history.NewChatHistoryService(db)
	appService := service2.NewAppService(yiKouAiCodegenFacade, userService, chatHistoryService, db)
	appHandler := handler.NewAppHandler(appService, userService, chatHistoryService)
	userHandler := handler2.NewUserHandler(userService)
	staticResourceHandler := static.NewStaticResourceHandler()
	hertz := InitServer(configConfig, appHandler, userHandler, staticResourceHandler, db)
	return hertz, nil
}

// wire.go:

// 配置依赖
var configSet = wire.NewSet(config.InitConfig)

// 数据库依赖
var dbSet = wire.NewSet(dal.InitDB)

// Service依赖
var serviceSet = wire.NewSet(core.NewYiKouAiCodegenFacade, service2.NewAppService, wire.Bind(new(service2.IAppService), new(*service2.AppService)), service.NewUserService, wire.Bind(new(service.IUserService), new(*service.UserService)), chat_history.NewChatHistoryService, wire.Bind(new(chat_history.IChatHistoryService), new(*chat_history.ChatHistoryService)))

// Handler依赖
var handlerSet = wire.NewSet(handler.NewAppHandler, handler2.NewUserHandler, static.NewStaticResourceHandler)

// Server依赖
func InitServer(
	serverConfig *config.Config,
	appHandler *handler.AppHandler,
	userHandler *handler2.UserHandler,
	staticResourceHandler *static.StaticResourceHandler,
	db *gorm.DB,
) *server.Hertz {
	basePath := serverConfig.Server.ContextPath
	docs.SwaggerInfo.
		BasePath = basePath

	swaggerPath := fmt.Sprintf("http://localhost:%d%s/swagger/doc.json", serverConfig.Server.Port, basePath)
	url := swagger.URL(swaggerPath)
	h := server.Default(server.WithHostPorts(":"+strconv.Itoa(serverConfig.Server.Port)), server.WithBasePath(serverConfig.Server.ContextPath))

	h.Use(cors.New(cors.Config{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: false,
		MaxAge:           12 * time.Hour,
	}))
	router.CustomizedRegister(h, db, appHandler, userHandler, staticResourceHandler, url)
	return h
}
