// Code generated by Kitex v0.16.1. DO NOT EDIT.

package chathistory

import (
	"context"

	"github.com/cloudwego/prutal"
)

type LoadChatHistoryToMemoryRequest struct {
	AppId int64 `protobuf:"varint,1,opt,name=appId" json:"appId,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (x *LoadChatHistoryToMemoryRequest) Reset() { *x = LoadChatHistoryToMemoryRequest{} }

func (x *LoadChatHistoryToMemoryRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *LoadChatHistoryToMemoryRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoadChatHistoryToMemoryRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *LoadChatHistoryToMemoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LoadChatHistoryToMemoryResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *LoadChatHistoryToMemoryResponse) Reset() { *x = LoadChatHistoryToMemoryResponse{} }

func (x *LoadChatHistoryToMemoryResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *LoadChatHistoryToMemoryResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoadChatHistoryToMemoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ChatHistoryService interface {
	LoadChatHistoryToMemory(ctx context.Context, req *LoadChatHistoryToMemoryRequest) (res *LoadChatHistoryToMemoryResponse, err error)
}
