// Code generated by Kitex v0.16.1. DO NOT EDIT.

package screenshotservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	kitex_gen "yikou-ai-go-microservice/services/screenshot/kitex_gen"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GenerateAndUploadScreenshot(ctx context.Context, Req *kitex_gen.GenerateAndUploadScreenshotRequest, callOptions ...callopt.Option) (r *kitex_gen.GenerateAndUploadScreenshotResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kScreenshotServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kScreenshotServiceClient struct {
	*kClient
}

func (p *kScreenshotServiceClient) GenerateAndUploadScreenshot(ctx context.Context, Req *kitex_gen.GenerateAndUploadScreenshotRequest, callOptions ...callopt.Option) (r *kitex_gen.GenerateAndUploadScreenshotResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateAndUploadScreenshot(ctx, Req)
}
