// Code generated by Kitex v0.16.1. DO NOT EDIT.

package screenshotservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	kitex_gen "yikou-ai-go-microservice/services/screenshot/kitex_gen"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenerateAndUploadScreenshot": kitex.NewMethodInfo(
		generateAndUploadScreenshotHandler,
		newGenerateAndUploadScreenshotArgs,
		newGenerateAndUploadScreenshotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	screenshotServiceServiceInfo                = NewServiceInfo()
	screenshotServiceServiceInfoForClient       = NewServiceInfoForClient()
	screenshotServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return screenshotServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return screenshotServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return screenshotServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ScreenshotService"
	handlerType := (*kitex_gen.ScreenshotService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "yikou.user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func generateAndUploadScreenshotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GenerateAndUploadScreenshotRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.ScreenshotService).GenerateAndUploadScreenshot(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenerateAndUploadScreenshotArgs:
		success, err := handler.(kitex_gen.ScreenshotService).GenerateAndUploadScreenshot(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenerateAndUploadScreenshotResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenerateAndUploadScreenshotArgs() interface{} {
	return &GenerateAndUploadScreenshotArgs{}
}

func newGenerateAndUploadScreenshotResult() interface{} {
	return &GenerateAndUploadScreenshotResult{}
}

type GenerateAndUploadScreenshotArgs struct {
	Req *kitex_gen.GenerateAndUploadScreenshotRequest
}

func (p *GenerateAndUploadScreenshotArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenerateAndUploadScreenshotArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateAndUploadScreenshotRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenerateAndUploadScreenshotArgs_Req_DEFAULT *kitex_gen.GenerateAndUploadScreenshotRequest

func (p *GenerateAndUploadScreenshotArgs) GetReq() *kitex_gen.GenerateAndUploadScreenshotRequest {
	if !p.IsSetReq() {
		return GenerateAndUploadScreenshotArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenerateAndUploadScreenshotArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenerateAndUploadScreenshotArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenerateAndUploadScreenshotResult struct {
	Success *kitex_gen.GenerateAndUploadScreenshotResponse
}

var GenerateAndUploadScreenshotResult_Success_DEFAULT *kitex_gen.GenerateAndUploadScreenshotResponse

func (p *GenerateAndUploadScreenshotResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenerateAndUploadScreenshotResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GenerateAndUploadScreenshotResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenerateAndUploadScreenshotResult) GetSuccess() *kitex_gen.GenerateAndUploadScreenshotResponse {
	if !p.IsSetSuccess() {
		return GenerateAndUploadScreenshotResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenerateAndUploadScreenshotResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GenerateAndUploadScreenshotResponse)
}

func (p *GenerateAndUploadScreenshotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenerateAndUploadScreenshotResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenerateAndUploadScreenshot(ctx context.Context, Req *kitex_gen.GenerateAndUploadScreenshotRequest) (r *kitex_gen.GenerateAndUploadScreenshotResponse, err error) {
	var _args GenerateAndUploadScreenshotArgs
	_args.Req = Req
	var _result GenerateAndUploadScreenshotResult
	if err = p.c.Call(ctx, "GenerateAndUploadScreenshot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
