// Code generated by hertz generator.

package router

import (
	"time"
	service "workspace-yikou-ai-go/biz/service/user"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/swagger"
	"github.com/redis/go-redis/v9"
	swaggerFiles "github.com/swaggo/files"
	"gorm.io/gorm"

	"workspace-yikou-ai-go/biz/cache"
	"workspace-yikou-ai-go/biz/handler"
	app "workspace-yikou-ai-go/biz/handler/app"
	chatHistory "workspace-yikou-ai-go/biz/handler/chathistory"
	"workspace-yikou-ai-go/biz/handler/static"
	user "workspace-yikou-ai-go/biz/handler/user"
	workflow "workspace-yikou-ai-go/biz/handler/workflow"
	"workspace-yikou-ai-go/biz/middleware"
	"workspace-yikou-ai-go/biz/model/enum"
	_ "workspace-yikou-ai-go/docs"
)

// CustomizedRegister registers customize routers.
func CustomizedRegister(r *server.Hertz, db *gorm.DB, redisClient *redis.Client, appHandler *app.AppHandler, userHandler *user.UserHandler,
	chatHistoryHandler *chatHistory.ChatHistoryHandler, staticHandler *static.StaticResourceHandler, workflowHandler *workflow.WorkflowHandler,
	cacheManager *cache.CacheManager, userService service.IUserService, url func(config *swagger.Config)) {
	r.GET("/ping", handler.Ping)
	r.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler, url))

	userRoute := r.Group("/user")
	{
		userRoute.POST("/register", userHandler.UserRegister)
		userRoute.POST("/login", userHandler.UserLogin)
		userRoute.GET("/get/vo", userHandler.GetUserVo)

		// 需要登录的接口
		userRoute.GET("/get/login", middleware.AuthMiddleware(enum.UserRole, db, redisClient), userHandler.GetLoginUser)
		userRoute.POST("/logout", middleware.AuthMiddleware(enum.UserRole, db, redisClient), userHandler.Logout)

		// 需要管理员权限的接口
		userRoute.POST("/add", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.AddUser)
		userRoute.GET("/get", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.GetUser)
		userRoute.POST("/delete", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.DeleteUser)
		userRoute.POST("/update", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.UpdateUser)
		userRoute.POST("/list/page/vo", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), userHandler.ListUserVoByPage)
	}

	appRoute := r.Group("/app")
	{
		appRoute.POST("/good/list/page/vo", middleware.CacheMiddleware(cacheManager, middleware.CacheMiddlewareConfig{
			CacheName:  "good_app_page",
			TTL:        5 * time.Minute,
			KeyBuilder: middleware.DefaultKeyBuilder,
			Condition:  middleware.PageCondition(10),
		}), appHandler.ListGoodApp)
		appRoute.GET("/get/vo", middleware.AuthMiddleware(enum.UserRole, db, redisClient), appHandler.GetAppVo)

		// 需要登录的接口
		appRoute.POST("/my/list/page/vo", middleware.AuthMiddleware(enum.UserRole, db, redisClient), appHandler.ListMyApp)
		appRoute.POST("/add", middleware.AuthMiddleware(enum.UserRole, db, redisClient), appHandler.AddApp)
		appRoute.POST("/update", middleware.AuthMiddleware(enum.UserRole, db, redisClient), appHandler.UpdateApp)
		appRoute.POST("/delete", middleware.AuthMiddleware(enum.UserRole, db, redisClient), appHandler.DeleteApp)
		appRoute.GET("/chat/gen/code", middleware.AuthMiddleware(enum.UserRole, db, redisClient),
			middleware.RateLimitMiddleware(redisClient, userService, middleware.RateLimitConfig{
				Rate:         5,
				RateInterval: 60,
				LimitType:    middleware.RateLimitTypeUSER,
				Message:      "AI对话请求过于频繁，请稍后再试",
			}), appHandler.ChatToGenCode)
		appRoute.POST("/chat/gen/stop", middleware.AuthMiddleware(enum.UserRole, db, redisClient), appHandler.StopStream)
		appRoute.POST("/deploy", middleware.AuthMiddleware(enum.UserRole, db, redisClient), appHandler.DeployApp)
		appRoute.GET("/download/:appId", middleware.AuthMiddleware(enum.UserRole, db, redisClient), appHandler.DownloadAppCode)

		// 需要管理员权限的接口
		appRoute.POST("/admin/update", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), appHandler.AdminUpdateApp)
		appRoute.POST("/admin/delete", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), appHandler.AdminDeleteApp)
		appRoute.GET("/admin/get/vo", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), appHandler.AdminGetAppVo)
		appRoute.POST("/admin/list/page/vo", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), appHandler.AdminListApp)
	}

	staticRoute := r.Group("/static")
	{
		staticRoute.GET("/:deployKey/*filepath", staticHandler.ServeStaticResource)
	}

	// 聊天历史路由
	chatHistoryRoute := r.Group("/chatHistory")
	{
		// 需要管理员权限的接口
		chatHistoryRoute.POST("/admin/list/page/vo", middleware.AuthMiddleware(enum.AdminRole, db, redisClient), chatHistoryHandler.ListAllChatHistoryByPageForAdmin)

		chatHistoryRoute.GET("/app/:appId", middleware.AuthMiddleware(enum.UserRole, db, redisClient), chatHistoryHandler.ListAppChatHistory)
	}

	workflowRoute := r.Group("/workflow")
	{
		workflowRoute.POST("/execute", middleware.AuthMiddleware(enum.UserRole, db, redisClient), workflowHandler.ExecuteWorkflow)
		workflowRoute.POST("execute-flux", middleware.AuthMiddleware(enum.UserRole, db, redisClient), workflowHandler.ExecuteWorkflow)
	}
}
